[package]
name = "byelines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simple_logger = "4.0.0"
regex = "1"
arboard = "3.2.0"
anyhow = "1.0.69"
mockall = "0.11.3"
